# training parameters
lr: 1e1
content_weight: 1e5
style_weight: 3e4
variance_weight: 1e0
optimizer: "lbfgs"
epochs: 1000
init_method: "content_img"

# style transfer options
style_layers: [0, 1, 2, 3, 5]
content_layers: [4]
normalize: True

# images and shapes
content_img: 'examples/content/prof.jpg'
style_img: 'examples/style/picasso2.jpg'
target_shape: [640, 480]

# img writing parameters
fps: 300
save_freq: 50
show: True

# paths
outputs: 'outputs'

# ignore, only for hydra
defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
